### ISSUE TITLE
Extend description of experience returned by method info(expid)

### ISSUE THREAD

**Issue by jcsombria** [UNEDLabs/rip-labview-server#11]
Currently, the method info(expid) gives a list of controls/indicators and their types, but it would be nice to have an extended description:
```javascript
{
  'info': {
    'name': 'The name of the experience',
    'description': 'A short description of the experience',
  },
  'methods':{
    'get':{
      'purpose':'The purpose of the method',
      'params':['variables':'[string]'],
    }
    ...
  },
  'readables':[['x','y',...],['number','string',...]],
  'writables':[['z','t',...],['number','string',...]],
}
```

**Comment by Ravenink** [comment]
I would also add authors in the info field:

```
'info': {
    'name': 'The name of the experience',
    'description': 'A short description of the experience',
    'authors':['Name Author 1', 'Name Author 2']
  },
```

readables and writables are already returned by the info(expid) method in the very same format as described by @jcsombria , right?

methods will always be the same for each lab, while the readables and writables lists are automatically constructed. info, however, requires the lab owner/developer to fill the information somewhere... I guess the Global_Configuration.vi is the propoper place for this?

Finally, how about adding a 'returns' field (in addition to 'purpose' -which maybe should be called description instead- and 'params') to the methods metadata?

**Comment by Ravenink** [comment]
@jcsombria I can see this issue is almost solved, but the methods metadata was still missing a 'returns' field for each method (get, set and info) listed there.
I have modified JSONRPC-BuildInfo.vi to add this field, however I need you to check if it is ok. I'm not convinced the method info should be returned in the metadata (as this metadata is obtained by calling the method info, so maybe its kind of dumb?).
Please check the changes (you can find them in the ServoMotor computer, I haven't uploaded them here) and do any required modification to exactly fit what the methods return. Then we can close this last issue.
